In [3]:
# import pandas library
import pandas as pd

# load data
df = pd.read_csv('EDA_Loan.csv')

In [6]:
# Indexing and Selection

#Access Column
print(df['Profession'])

# Access first row
print(df.loc[0])

# Access specific element
print(df.iloc[0, 1])

0                     Working
1                     Working
2                   Pensioner
3                   Pensioner
4                     Working
                 ...
29995    Commercial associate
29996                 Working
29997                 Working
29998                 Working
29999               Pensioner
Name: Profession, Length: 30000, dtype: object
Customer ID                             C-36995
Name                           Frederica Shealy
Gender                                        F
Age                                          56
Income (USD)                            1933.05
Income Stability                            Low
Profession                              Working
Type of Employment                  Sales staff
Location                             Semi-Urban
Loan Amount Request (USD)              72809.58
Current Loan Expenses (USD)              241.08
Expense Type 1                                N
Expense Type 2                                N
Dependents                                  3.0
Credit Score                             809.44
No. of Defaults                               0
Has Active Credit Card                      NaN
Property ID                                 746
Property Age                            1933.05
Property Type                                 4
Property Location                         Rural
Co-Applicant                                  1
Property Price                        119933.46
Loan Sanction Amount (USD)             54607.18
Name: 0, dtype: object
Frederica Shealy

In [ ]:
# Data Manipulation

# Rename column

df = df.rename(columns={'Income (USD)': 'Salary'})

# Fill missing values
df['Salary'] = df['Salary'].fillna(0)

# Drop column
df = df.drop(columns=['Age'])

In [16]:
#  Setting a Multi-Index

df.set_index(['Customer ID', 'Name'], inplace=True)
print(df)

                              Gender   Salary Income Stability  \
Customer ID Name
C-36995     Frederica Shealy       F  1933.05              Low
C-33999     America Calderone      M  4952.91              Low
C-3770      Rosetta Verne          F   988.19             High
C-26480     Zoe Chitty             F     0.00             High
C-23459     Afton Venema           F  2614.77              Low
...                              ...      ...              ...
C-43723     Angelyn Clevenger      M  4969.41              Low
C-32511     Silas Slaugh           M  1606.88              Low
C-5192      Carmelo Lone           F     0.00              Low
C-12172     Carolann Osby          M  2417.71              Low
C-33003     Bridget Garibaldi      F  3068.24             High

                                         Profession     Type of Employment  \
Customer ID Name
C-36995     Frederica Shealy                Working            Sales staff
C-33999     America Calderone               Working                    NaN
C-3770      Rosetta Verne                 Pensioner                    NaN
C-26480     Zoe Chitty                    Pensioner                    NaN
C-23459     Afton Venema                    Working  High skill tech staff
...                                             ...                    ...
C-43723     Angelyn Clevenger  Commercial associate               Managers
C-32511     Silas Slaugh                    Working               Laborers
C-5192      Carmelo Lone                    Working            Sales staff
C-12172     Carolann Osby                   Working         Security staff
C-33003     Bridget Garibaldi             Pensioner                    NaN

                                 Location  Loan Amount Request (USD)  \
Customer ID Name
C-36995     Frederica Shealy   Semi-Urban                   72809.58
C-33999     America Calderone  Semi-Urban                   46837.47
C-3770      Rosetta Verne      Semi-Urban                   45593.04
C-26480     Zoe Chitty              Rural                   80057.92
C-23459     Afton Venema       Semi-Urban                  113858.89
...                                   ...                        ...
C-43723     Angelyn Clevenger       Urban                   76657.90
C-32511     Silas Slaugh       Semi-Urban                   66595.14
C-5192      Carmelo Lone            Urban                   81410.08
C-12172     Carolann Osby      Semi-Urban                  142524.10
C-33003     Bridget Garibaldi       Rural                  156290.54

                               Current Loan Expenses (USD) Expense Type 1  \
Customer ID Name
C-36995     Frederica Shealy                        241.08              N
C-33999     America Calderone                       495.81              N
C-3770      Rosetta Verne                           171.95              N
C-26480     Zoe Chitty                              298.54              N
C-23459     Afton Venema                            491.41              N
...                                                    ...            ...
C-43723     Angelyn Clevenger                       722.34              Y
C-32511     Silas Slaugh                            253.04              N
C-5192      Carmelo Lone                            583.11              N
C-12172     Carolann Osby                           378.29              N
C-33003     Bridget Garibaldi                       693.94              N

                              Expense Type 2  ...  Credit Score  \
Customer ID Name                              ...
C-36995     Frederica Shealy               N  ...        809.44
C-33999     America Calderone              Y  ...        780.40
C-3770      Rosetta Verne                  Y  ...        833.15
C-26480     Zoe Chitty                     Y  ...        832.70
C-23459     Afton Venema                   Y  ...        745.55
...                                      ...  ...           ...
C-43723     Angelyn Clevenger              Y  ...        869.61
C-32511     Silas Slaugh                   N  ...        729.41
C-5192      Carmelo Lone                   Y  ...           NaN
C-12172     Carolann Osby                  Y  ...        677.27
C-33003     Bridget Garibaldi              Y  ...        815.44

                               No. of Defaults  Has Active Credit Card  \
Customer ID Name
C-36995     Frederica Shealy                 0                     NaN
C-33999     America Calderone                0             Unpossessed
C-3770      Rosetta Verne                    0             Unpossessed
C-26480     Zoe Chitty                       1             Unpossessed
C-23459     Afton Venema                     1                  Active
...                                        ...                     ...
C-43723     Angelyn Clevenger                0             Unpossessed
C-32511     Silas Slaugh                     0                Inactive
C-5192      Carmelo Lone                     0                  Active
C-12172     Carolann Osby                    1             Unpossessed
C-33003     Bridget Garibaldi                0                  Active

                              Property ID  Property Age  Property Type  \
Customer ID Name
C-36995     Frederica Shealy          746       1933.05              4
C-33999     America Calderone         608       4952.91              2
C-3770      Rosetta Verne             546        988.19              2
C-26480     Zoe Chitty                890           NaN              2
C-23459     Afton Venema              715       2614.77              4
...                                   ...           ...            ...
C-43723     Angelyn Clevenger         566       4969.41              4
C-32511     Silas Slaugh              175       1606.88              3
C-5192      Carmelo Lone              959           NaN              1
C-12172     Carolann Osby             375       2417.71              4
C-33003     Bridget Garibaldi         344       3068.24              3

                               Property Location Co-Applicant  Property Price  \
Customer ID Name
C-36995     Frederica Shealy               Rural            1       119933.46
C-33999     America Calderone              Rural            1        54791.00
C-3770      Rosetta Verne                  Urban            0        72440.58
C-26480     Zoe Chitty                Semi-Urban            1       121441.51
C-23459     Afton Venema              Semi-Urban            1       208567.91
...                                          ...          ...             ...
C-43723     Angelyn Clevenger              Urban            1       111096.56
C-32511     Silas Slaugh                   Urban            1        73453.94
C-5192      Carmelo Lone                   Rural            1       102108.02
C-12172     Carolann Osby                  Urban            1       168194.47
C-33003     Bridget Garibaldi              Rural            1       194512.60

                               Loan Sanction Amount (USD)
Customer ID Name
C-36995     Frederica Shealy                     54607.18
C-33999     America Calderone                    37469.98
C-3770      Rosetta Verne                        36474.43
C-26480     Zoe Chitty                           56040.54
C-23459     Afton Venema                         74008.28
...                                                   ...
C-43723     Angelyn Clevenger                    68992.11
C-32511     Silas Slaugh                         46616.60
C-5192      Carmelo Lone                         61057.56
C-12172     Carolann Osby                        99766.87
C-33003     Bridget Garibaldi                   117217.90

[30000 rows x 21 columns]